### ISSUE TITLE
FR : Ability to export to/import from file

### ISSUE THREAD

**Issue by tipiak75** [Jormund/bookmarkstore#1]
As I recently experienced, localstorage is not a reliable long-term data storage solution (a browser profile reset or any other catastrophic event could happen and erase all saved bookmark data forever), so I figured a file export feature could be useful, as well as a symetrical import feature for data restoration purposes in case some disaster happens.

**Comment by Jormund** [comment]
Regarding generic localStorage export for intel, I can recommend http://www.giacintogarcea.com/ingress/iitc/localstorage-manager-by-zaso.user.js
I'll see what I can do for bookmarkstore. I'll probably make a text export like bookmark has already.

**Comment by Jormund** [comment]
I added the same options as bookmarks plugin: Reset, Copy, Paste on all devices and Import/Export on mobile.
